# -*- coding: utf-8 -*-
"""SteadyStepModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i1L37FIKVtRHR83DX0Y2W2tq_j4YPxcr

#Import Libraries
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.metrics import root_mean_squared_error, mean_absolute_error, recall_score, accuracy_score, roc_auc_score, confusion_matrix, classification_report
from sklearn.ensemble import BaggingRegressor, BaggingClassifier, RandomForestRegressor, RandomForestClassifier
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.model_selection import train_test_split, KFold, RepeatedKFold, GridSearchCV, StratifiedKFold, cross_val_predict, RandomizedSearchCV

from lightgbm import LGBMRegressor, LGBMClassifier
from sklearn.preprocessing import StandardScaler

import os
from tqdm.notebook import tqdm
import time

# Step Count
from scipy.signal import find_peaks, butter, filtfilt

"""#Data Cleaning"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("letmecook123/mpu6050-body-movement-dataset-walking-running-idle")

print("Path to dataset files:", path)

path = "/root/.cache/kagglehub/datasets/letmecook123/mpu6050-body-movement-dataset-walking-running-idle/versions/1"

cols = ["timestamp", "accel_x", "accel_y", "accel_z",
        "gyro_x", "gyro_y", "gyro_z", "temperature", "label"]

# Load one specific file (replace with actual filename from the ls above)
walking_df = pd.read_csv(os.path.join(path, "walking.csv"), header=None, names=cols)
idle_df = pd.read_csv(os.path.join(path, "idle.csv"), header=None, names=cols)
running_df = pd.read_csv(os.path.join(path, "running.csv"), header=None, names=cols)

walking_df['label'] = 'walking'
idle_df['label'] = 'idle'
running_df['label'] = 'running'

all_data = pd.concat([walking_df, running_df, idle_df], axis=0)

y=all_data['label']
X=all_data.drop('label', axis=1)
walking_dfy = walking_df['label']
walking_dfX = walking_df.drop('label', axis=1)
running_dfy = running_df['label']
running_dfX = running_df.drop('label', axis=1)
idle_dfy = idle_df['label']
idle_dfX = idle_df.drop('label', axis=1)

def add_magnitude(data, magnitude_groups):
    """
    Append magnitude channels to the dataframe.

    magnitude_groups: {new_col_name: [axis_columns]}
        e.g. {'accel_mag': ['accel_x', 'accel_y', 'accel_z']}
    """
    data = data.copy()
    for new_col, axes in magnitude_groups.items():
        data[new_col] = np.sqrt(np.sum(data[axes].values ** 2, axis=1))
    return data


def raw_to_windows(data, window_size, step, sample_rate,
                   freq_bands=((0.5, 3.0), (3.0, 6.0))):
    """
    Slide a window over `data` and compute time- and frequency-domain features per column.

    sample_rate: Hz of the input signal (needed to map FFT bins to Hz)
    freq_bands:  list of (low, high) Hz pairs for spectral energy features
    """
    rows = []
    cols = list(data.columns)
    freqs = np.fft.rfftfreq(window_size, d=1.0 / sample_rate)

    for start in range(0, len(data) - window_size + 1, step):
        window = data.iloc[start:start + window_size]
        feats = {'window_start': start}

        for col in cols:
            x = window[col].values

            # Time-domain
            feats[f'{col}_mean']  = x.mean()
            feats[f'{col}_std']   = x.std()
            feats[f'{col}_min']   = x.min()
            feats[f'{col}_max']   = x.max()
            feats[f'{col}_range'] = x.max() - x.min()
            feats[f'{col}_rms']   = np.sqrt(np.mean(x ** 2))

            # Frequency-domain (subtract mean to drop DC)
            spec = np.abs(np.fft.rfft(x - x.mean()))

            # Dominant frequency (skip DC bin)
            dom_bin = 1 + np.argmax(spec[1:]) if len(spec) > 1 else 0
            feats[f'{col}_dom_freq'] = freqs[dom_bin]

            # Spectral energy per band
            for low, high in freq_bands:
                mask = (freqs >= low) & (freqs < high)
                feats[f'{col}_energy_{low}-{high}Hz'] = np.sum(spec[mask] ** 2)

        rows.append(feats)

    return pd.DataFrame(rows)

def raw_to_window(data, window_size, overlap):
  window_start = 0
  return_data = pd.DataFrame()
  # Create window
  while window_start <= data.shape[0] - window_size:
    window_end = window_start + window_size
    window_end = window_start + window_size
    window = data.iloc[window_start:window_end, :]
    # For each value (accel/gyro x,y,z), calculate the terms
    return_for_window = pd.DataFrame()
    for col in window.columns:
      return_for_window.loc[0, col + '_mean'] = window[col].mean()
      return_for_window.loc[0,col + '_std'] = window[col].std()
      return_for_window.loc[0,col + '_min'] = window[col].min()
      return_for_window.loc[0,col + '_max'] = window[col].max()
      return_for_window.loc[0,col + '_range'] = window[col].max() - window[col].min()
      return_for_window.loc[0,col + '_rms'] = np.sqrt(np.mean(np.square(window[col])))
    return_data = pd.concat([return_data, return_for_window])
    window_start += overlap
  return return_data

def add_col_of(df, label):
  copy_df = df
  copy_df['label'] = label
  return copy_df['label']

def extract_features(dataset, window_size=200, step=100, sample_rate=100):
  raw_imu = dataset.copy()
  data = add_magnitude(raw_imu, {
    'accel_mag': ['accel_x', 'accel_y', 'accel_z'],
    'gyro_mag':  ['gyro_x',  'gyro_y',  'gyro_z'],})
  features = raw_to_windows(data, window_size, step, sample_rate)
  return features

walking_dfX_Train = extract_features(walking_dfX, 100, 50)
running_dfX_Train = extract_features(running_dfX, 100, 50)
idle_dfX_Train = extract_features(idle_dfX, 100, 50)

# walking_dfX_Test = raw_to_window(X_Walking_test, 100, 50)
# running_dfX_Test = raw_to_window(X_Running_test, 100, 50)
# idle_dfX_Test = raw_to_window(X_Idle_test, 100, 50)

X = pd.concat([walking_dfX_Train, running_dfX_Train, idle_dfX_Train], axis=0)
y = pd.concat([add_col_of(walking_dfX_Train, "walking"), add_col_of(running_dfX_Train, "running"), add_col_of(idle_dfX_Train, "idle")])
# y = pd.concat([walking_dfX_Test, running_dfX_Test, idle_dfX_Test], axis=0)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=20, stratify = y)
scaler = StandardScaler()

scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

# model_light = LGBMClassifier(random_state = 1, class_weight='balanced', verbose = -1)

# grid_light = {
#     'max_depth': [4, 6, 8],
#     'n_estimators': [50, 100, 200],
#     'learning_rate': [0.05, 0.1],
#     'subsample': [0.8, 1.0],
#     'reg_lambda': [0.1, 1, 10],
#     'colsample_bytree': [0.8, 1.0],
# }

# rscv = RandomizedSearchCV(model_light, grid_light, n_iter=60, cv=5,
#                           scoring='roc_auc_ovr', n_jobs=-1, random_state=1)
# rscv.fit(X_train, y_train)

tuned_random_lgbm = rscv.best_estimator_
print("Best avg CV AUC:", rscv.best_score_)
print("Best params:", rscv.best_params_)

# Get probabilities for ALL classes (shape: n_samples × 3)
y_test_pred_light = tuned_random_lgbm.predict_proba(X_test)

# Specify multi-class strategy — match what you used in GridSearch (ovr or ovo)
print("Test AUC:", roc_auc_score(y_test, y_test_pred_light, multi_class='ovr'))

y_test

y_test_pred_class = tuned_random_lgbm.predict(X_test)  # actual predicted labels

print("Test accuracy:", accuracy_score(y_test, y_test_pred_class))
print("\nClassification report:")
print(classification_report(y_test, y_test_pred_class))
print("Confusion matrix:")
print(confusion_matrix(y_test, y_test_pred_class))

walking_dfX

def detect_steps(data, fs=50):
    mag = np.sqrt(data['accel_x']**2 + data['accel_y']**2 + data['accel_z']**2)
    b, a = butter(4, [0.5, 3.0], btype='band', fs=fs)
    mag_filt = filtfilt(b, a, mag - mag.mean())

    # Adaptive threshold: only count peaks that stand out from typical noise
    threshold = mag_filt.std() * 1.0   # tune 1.0 → 1.5 if still over-counting

    peaks, _ = find_peaks(
        mag_filt,
        height=threshold,
        distance=int(0.3 * fs),   # min 0.3 s between steps
        prominence=threshold * 0.5,  # peak must "stick up" from local baseline
    )
    return peaks, mag_filt

peaks, _ = detect_steps(idle_df, fs=50)
total_steps = len(peaks)

total_steps

peaks, mag_filt = detect_steps(running_df.iloc[:500], fs=50)  # first 10s at 50Hz
plt.figure(figsize=(12, 4))
plt.plot(mag_filt)
plt.plot(peaks, mag_filt[peaks], 'rx', markersize=12)
plt.title(f"{len(peaks)} steps detected in 10 seconds → {len(peaks)*6} spm")
plt.show()

peaks, mag_filt = detect_steps(idle_df.iloc[:1000], fs=50)  # first 10s at 50Hz
plt.figure(figsize=(12, 4))
plt.plot(mag_filt)
plt.plot(peaks, mag_filt[peaks], 'rx', markersize=12)
plt.title(f"{len(peaks)} steps detected in 10 seconds → {len(peaks)*6} spm")
plt.show()

total_steps = len(peaks)
duration_min = (walking_df['timestamp'].iloc[-1] - walking_df['timestamp'].iloc[0]) / 60
cadence = total_steps / duration_min  # steps per minute

def detect_stance_phases(data, fs=50, accel_var_thresh=None, gyro_mag_thresh=None):
    """
    Stance phase = foot is flat on ground = low gyro magnitude AND low accel variance.
    Returns a boolean array, True where the foot is in stance.
    """
    gyro_mag = np.sqrt(data['gyro_x']**2 + data['gyro_y']**2 + data['gyro_z']**2)
    accel_mag = np.sqrt(data['accel_x']**2 + data['accel_y']**2 + data['accel_z']**2)

    # Rolling variance of accel magnitude over a small window (~50 ms)
    win = max(int(0.05 * fs), 3)
    accel_var = pd.Series(accel_mag).rolling(win, center=True).var().fillna(0).values

    # Adaptive thresholds if not supplied
    if gyro_mag_thresh is None:
        gyro_mag_thresh = np.percentile(gyro_mag, 30)
    if accel_var_thresh is None:
        accel_var_thresh = np.percentile(accel_var, 30)

    stance = (gyro_mag < gyro_mag_thresh) & (accel_var < accel_var_thresh)
    return stance


def estimate_foot_clearance(data, fs=50, gravity_raw=16384):
    """
    Estimate per-step foot clearance using ZUPT.

    `gravity_raw`: raw accel value corresponding to 1 g. For MPU6050 at ±2g range,
    this is 16384. Adjust if your sensor is configured differently.

    Returns: list of clearance heights (in meters), one per stride.
    """
    # 1. Convert raw accel to m/s²  (raw → g → m/s²)
    g = 9.81
    ax = data['accel_x'].values / gravity_raw * g
    ay = data['accel_y'].values / gravity_raw * g
    az = data['accel_z'].values / gravity_raw * g

    # 2. Acceleration magnitude minus gravity. We're not doing full orientation
    # tracking here, so we approximate vertical accel as (|a| - g).
    # For better accuracy, integrate gyro to track orientation and rotate the
    # accel vector into the world frame. This simple version works decently for
    # foot-mounted sensors where the foot is roughly level during swing.
    a_mag = np.sqrt(ax**2 + ay**2 + az**2)
    a_vert = a_mag - g

    # 3. Find stance phases
    stance = detect_stance_phases(data, fs=fs)

    # 4. Integrate acceleration → velocity → position, resetting at each stance
    dt = 1.0 / fs
    velocity = np.zeros(len(a_vert))
    position = np.zeros(len(a_vert))

    clearances = []
    in_swing = False
    swing_start = 0

    for i in range(1, len(a_vert)):
        if stance[i]:
            # Foot on ground — reset velocity, mark end of swing if we were in one
            if in_swing:
                # Find max height during the swing we just finished
                swing_height = position[swing_start:i].max() - position[swing_start]
                clearances.append(swing_height)
                in_swing = False
            velocity[i] = 0.0
            position[i] = position[i - 1]   # don't drift while planted
        else:
            # Swing phase — integrate
            if not in_swing:
                in_swing = True
                swing_start = i
                position[i] = position[i - 1]   # start swing from last stance height
            velocity[i] = velocity[i - 1] + a_vert[i] * dt
            position[i] = position[i - 1] + velocity[i] * dt

    return np.array(clearances)


# Usage
clearances = estimate_foot_clearance(walking_df, fs=50)
print(f"Mean foot clearance: {clearances.mean()*100:.1f} cm")
print(f"Min clearance: {clearances.min()*100:.1f} cm")
print(f"Max clearance: {clearances.max()*100:.1f} cm")

def gait_similarity(peaks, fs=50):
    """
    Score 1-10 measuring how regular the user's gait is.
    Higher = more consistent stride timing = lower fall risk.

    Built from:
      - CV of step intervals (timing consistency)
      - Asymmetry between left/right step intervals (limp detection)
    """
    if len(peaks) < 4:
        return None, "Not enough steps to assess gait similarity"

    # Step intervals in seconds
    intervals = np.diff(peaks) / fs

    # 1. Coefficient of variation: lower = more regular
    cv = intervals.std() / intervals.mean()

    # 2. Asymmetry: in healthy gait, odd & even step intervals are similar
    #    (left-right-left-right gives roughly equal alternating intervals).
    #    A limp creates a long-short-long-short pattern.
    odd_intervals = intervals[::2]
    even_intervals = intervals[1::2]
    n = min(len(odd_intervals), len(even_intervals))
    if n >= 2:
        asymmetry = abs(odd_intervals[:n].mean() - even_intervals[:n].mean()) \
                    / intervals.mean()
    else:
        asymmetry = 0.0

    # 3. Map to a 1-10 score.
    # Healthy reference values from the literature:
    #   CV < 0.05 is excellent, > 0.15 is concerning
    #   Asymmetry < 0.05 is excellent, > 0.20 is concerning
    cv_score        = np.clip(1 - (cv - 0.03) / 0.17, 0, 1)        # 1 at cv=0.03, 0 at cv=0.20
    asym_score      = np.clip(1 - (asymmetry - 0.02) / 0.18, 0, 1) # 1 at asym=0.02, 0 at asym=0.20

    # Weighted combo — both matter, asymmetry slightly more for fall risk
    combined = 0.45 * cv_score + 0.55 * asym_score
    score_1_to_10 = 1 + 9 * combined   # rescale to 1-10

    diagnostics = {
        'cv': float(cv),
        'asymmetry': float(asymmetry),
        'mean_interval_s': float(intervals.mean()),
        'n_steps': int(len(peaks)),
    }
    return float(score_1_to_10), diagnostics


# Usage — peaks comes from your detect_steps()
peaks, _ = detect_steps(walking_df, fs=50)
score, diag = gait_similarity(peaks, fs=50)
print(f"Gait similarity score: {score:.1f} / 10")
print(f"Diagnostics: {diag}")

def classify_gait(cadence, mean_clearance_cm, asymmetry, cv):
    # Asymmetry is the strongest signal for limping
    if asymmetry > 0.15:
        return "Limping", min(asymmetry / 0.30, 1.0)
    # Shuffling: low foot clearance, often paired with high-frequency short steps
    if mean_clearance_cm < 5 and cadence > 110:
        return "Shuffling", min((10 - mean_clearance_cm) / 10, 1.0)
    # High CV without clear asymmetry → general unsteadiness
    if cv > 0.12:
        return "Unsteady", min(cv / 0.20, 1.0)
    return "Normal", 1.0 - max(cv / 0.10, asymmetry / 0.10, 0)

import joblib

# Save
joblib.dump(tuned_random_lgbm, 'gait_model.pkl')
joblib.dump(scaler, 'scaler.pkl')

# Load later
model = joblib.load('gait_model.pkl')
scaler = joblib.load('scaler.pkl')

import json
import lightgbm as lgb
import sklearn


metadata = {
    'feature_columns': list(X_train.columns),
    'classes': list(tuned_random_lgbm.classes_),
    'sampling_rate_hz': 50,
    'window_size': 100,
    'overlap': 50,
    'lightgbm_version': lgb.__version__,
    'sklearn_version': sklearn.__version__,
}
with open('model_metadata.json', 'w') as f:
    json.dump(metadata, f, indent=2)

# Reload from disk
loaded_model = joblib.load('gait_model.pkl')
loaded_scaler = joblib.load('scaler.pkl')

# Wrap BOTH in named DataFrames so the comparison is apples-to-apples
X_test_named = pd.DataFrame(
    loaded_scaler.transform(X_test),
    columns=X_test.columns,
    index=X_test.index,
)

original_preds = tuned_random_lgbm.predict_proba(X_test_named)
loaded_preds = loaded_model.predict_proba(X_test_named)

assert np.allclose(original_preds, loaded_preds), "Model didn't reload cleanly!"
print("✓ Model saved and reloaded correctly")

print(loaded_preds)